name: bazel (vm bento)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - self-hosted
    - "os=linux"
    - "engflow-cluster=local"
    - "engflow-bento-allow-save=true"
    - "engflow-bento-vm-base-image=ubuntu-24.04"
    - "engflow-bento-branch=main"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run bazel
      run: |
        bazel info
